// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `RpcManagedObject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <RpcManagedObject.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Rpc__ManagedObject__destroy_name = "destroy";

}
::IceProxy::Ice::Object* ::IceProxy::Rpc::upCast(::IceProxy::Rpc::ManagedObject* p) { return p; }

void
::IceProxy::Rpc::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Rpc::ManagedObject>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Rpc::ManagedObject;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Rpc::ManagedObject::destroy(const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __Rpc__ManagedObject__destroy_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::Rpc::ManagedObject::begin_destroy(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Rpc__ManagedObject__destroy_name, __del, __cookie);
    try
    {
        __result->prepare(__Rpc__ManagedObject__destroy_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::Rpc::ManagedObject::end_destroy(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Rpc__ManagedObject__destroy_name);
}

const ::std::string&
IceProxy::Rpc::ManagedObject::ice_staticId()
{
    return ::Rpc::ManagedObject::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Rpc::ManagedObject::__newInstance() const
{
    return new ManagedObject;
}

::Ice::Object* Rpc::upCast(::Rpc::ManagedObject* p) { return p; }

namespace
{
const ::std::string __Rpc__ManagedObject_ids[2] =
{
    "::Ice::Object",
    "::Rpc::ManagedObject"
};

}

bool
Rpc::ManagedObject::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Rpc__ManagedObject_ids, __Rpc__ManagedObject_ids + 2, _s);
}

::std::vector< ::std::string>
Rpc::ManagedObject::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Rpc__ManagedObject_ids[0], &__Rpc__ManagedObject_ids[2]);
}

const ::std::string&
Rpc::ManagedObject::ice_id(const ::Ice::Current&) const
{
    return __Rpc__ManagedObject_ids[1];
}

const ::std::string&
Rpc::ManagedObject::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Rpc::ManagedObject";
    return typeId;
#else
    return __Rpc__ManagedObject_ids[1];
#endif
}

::Ice::DispatchStatus
Rpc::ManagedObject::___destroy(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    destroy(__current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Rpc__ManagedObject_all[] =
{
    "destroy",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
Rpc::ManagedObject::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Rpc__ManagedObject_all, __Rpc__ManagedObject_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Rpc__ManagedObject_all)
    {
        case 0:
        {
            return ___destroy(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Rpc::ManagedObject::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Rpc::ManagedObject::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Rpc::__patch(ManagedObjectPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Rpc::ManagedObjectPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Rpc::ManagedObject::ice_staticId(), v);
    }
}
