//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `RpcManagedObject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <RpcManagedObject.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_Rpc_ManagedObject_ids[2] =
{
    "::Ice::Object",
    "::Rpc::ManagedObject"
};
const ::std::string iceC_Rpc_ManagedObject_ops[] =
{
    "destroy",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Rpc_ManagedObject_destroy_name = "destroy";

}

bool
Rpc::ManagedObject::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Rpc_ManagedObject_ids, iceC_Rpc_ManagedObject_ids + 2, s);
}

::std::vector<::std::string>
Rpc::ManagedObject::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Rpc_ManagedObject_ids[0], &iceC_Rpc_ManagedObject_ids[2]);
}

::std::string
Rpc::ManagedObject::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Rpc::ManagedObject::ice_staticId()
{
    static const ::std::string typeId = "::Rpc::ManagedObject";
    return typeId;
}

/// \cond INTERNAL
bool
Rpc::ManagedObject::_iceD_destroy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->destroy(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Rpc::ManagedObject::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Rpc_ManagedObject_ops, iceC_Rpc_ManagedObject_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Rpc_ManagedObject_ops)
    {
        case 0:
        {
            return _iceD_destroy(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
Rpc::ManagedObjectPrx::_iceI_destroy(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Rpc_ManagedObject_destroy_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Rpc::ManagedObjectPrx::_newInstance() const
{
    return ::IceInternal::createProxy<ManagedObjectPrx>();
}
/// \endcond

const ::std::string&
Rpc::ManagedObjectPrx::ice_staticId()
{
    return ManagedObject::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_Rpc_ManagedObject_destroy_name = "destroy";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Rpc::upCast(ManagedObject* p) { return p; }

void
::IceProxy::Rpc::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ManagedObject>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ManagedObject;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Rpc::ManagedObject::_iceI_begin_destroy(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Rpc_ManagedObject_destroy_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Rpc_ManagedObject_destroy_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_Rpc_ManagedObject_destroy_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Rpc::ManagedObject::end_destroy(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Rpc_ManagedObject_destroy_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Rpc::ManagedObject::_newInstance() const
{
    return new ManagedObject;
}
/// \endcond

const ::std::string&
IceProxy::Rpc::ManagedObject::ice_staticId()
{
    return ::Rpc::ManagedObject::ice_staticId();
}

Rpc::ManagedObject::~ManagedObject()
{
}

/// \cond INTERNAL
::Ice::Object* Rpc::upCast(ManagedObject* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Rpc_ManagedObject_ids[2] =
{
    "::Ice::Object",
    "::Rpc::ManagedObject"
};

}

bool
Rpc::ManagedObject::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Rpc_ManagedObject_ids, iceC_Rpc_ManagedObject_ids + 2, s);
}

::std::vector< ::std::string>
Rpc::ManagedObject::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Rpc_ManagedObject_ids[0], &iceC_Rpc_ManagedObject_ids[2]);
}

const ::std::string&
Rpc::ManagedObject::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Rpc::ManagedObject::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Rpc::ManagedObject";
    return typeId;
#else
    return iceC_Rpc_ManagedObject_ids[1];
#endif
}

/// \cond INTERNAL
bool
Rpc::ManagedObject::_iceD_destroy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->destroy(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Rpc_ManagedObject_all[] =
{
    "destroy",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
Rpc::ManagedObject::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Rpc_ManagedObject_all, iceC_Rpc_ManagedObject_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Rpc_ManagedObject_all)
    {
        case 0:
        {
            return _iceD_destroy(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Rpc::ManagedObject::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< ManagedObject, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Rpc::ManagedObject::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< ManagedObject, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Rpc::_icePatchObjectPtr(ManagedObjectPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ManagedObjectPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(ManagedObject::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
